package org.dieschnittstelle.jee.esa.jaxwsnew;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-09-22T18:44:50.442+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://dieschnittstelle.org/jee/esa/jaxwsNew", name = "ProductCRUDWebService")
@XmlSeeAlso({org.taeglichmahl.crm.model.data.ObjectFactory.class, ObjectFactory.class, org.dieschnittstelle.jee.esa.erp.model.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ProductCRUDWebService {

    @WebResult(name = "createProductResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/jaxwsNew", partName = "createProductResponse")
    @WebMethod
    public org.dieschnittstelle.jee.esa.erp.model.AbstractProduct createProduct(
        @WebParam(partName = "createProduct", name = "createProduct", targetNamespace = "http://dieschnittstelle.org/jee/esa/jaxwsNew")
        org.dieschnittstelle.jee.esa.erp.model.AbstractProduct createProduct
    );

    @WebResult(name = "readAllProductsResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/jaxwsNew", partName = "readAllProductsResponse")
    @WebMethod
    public org.dieschnittstelle.jee.esa.erp.model.AbstractProductArray readAllProducts();
}
