package org.dieschnittstelle.jee.esa.gae.client.views.sellers;

import java.util.List;

import org.dieschnittstelle.jee.esa.gae.client.common.AbstractView;
import org.dieschnittstelle.jee.esa.gae.shared.entities.dto.TouchpointDTO;

import com.google.gwt.core.client.GWT;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.client.ui.Grid;
import com.google.gwt.user.client.ui.Label;
import com.google.gwt.user.client.ui.Widget;
import com.google.inject.Inject;

public class SellersViewImpl extends AbstractView implements SellersView {

	@UiField
	protected Grid sellerstable;

	private List<TouchpointDTO> touchpoints;
	// @UiField
	// protected FlowPanel panelproduct;
	// @UiField
	// protected Grid producttable;

	private static ProductsViewImplUiBinder uiBinder = GWT
			.create(ProductsViewImplUiBinder.class);

	interface ProductsViewImplUiBinder extends
			UiBinder<Widget, SellersViewImpl> {
		// TODO Generated by GWT
	}

	private Presenter presenter;

	@Inject
	public SellersViewImpl() {
		content.add(uiBinder.createAndBindUi(this));
	}

	@Override
	public void setPresenter(final Presenter presenter) {
		this.presenter = presenter;
	}

	@Override
	public void setTouchpoints(List<TouchpointDTO> touchpoints) {
		this.touchpoints = touchpoints;
		setTouchpoints();

	}

	private void setTouchpoints() {
		sellerstable.clear();
		sellerstable = new Grid(touchpoints.size(), 2);
		sellerstable.setStyleName("tablep");
		int i = 0;
		if (touchpoints != null && !touchpoints.isEmpty()) {
			for (TouchpointDTO point : touchpoints) {

				sellerstable.setWidget(i, 0, new Label(point.getName() + ""));
				sellerstable.setWidget(i, 1, new Label(point.getAddress()
						.getCity()
						+ ", "
						+ point.getAddress().getStreet()
						+ " " + point.getAddress().getHouseNr()));
				i++;
			}
		} else {
			content.add(new Label("Keine Händler vorhanden"));
		}
		content.add(sellerstable);
	}

	// @UiHandler("button")
	// void onButtonPressed(ClickEvent e) {
	// Window.alert("Clicked Me");
	// }
}
