package org.dieschnittstelle.jee.esa.gae.client.views.login_registration;

import org.dieschnittstelle.jee.esa.gae.client.common.AbstractView;

import com.google.gwt.core.client.GWT;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.user.client.ui.Widget;
import com.google.inject.Inject;

public class RegistrationViewImpl extends AbstractView implements
		RegistrationView {

	private static RegistrationViewImplUiBinder uiBinder = GWT
			.create(RegistrationViewImplUiBinder.class);

	interface RegistrationViewImplUiBinder extends
			UiBinder<Widget, RegistrationViewImpl> {
		// TODO Generated by GWT
	}

	private Presenter presenter;

	@Inject
	public RegistrationViewImpl() {
		content.add(uiBinder.createAndBindUi(this));
	}

	@Override
	public void setPresenter(final Presenter presenter) {
		this.presenter = presenter;
	}

	// @UiHandler("button")
	// void onButtonPressed(ClickEvent e) {
	// Window.alert("Clicked Me");
	// }
}
